### ISSUE TITLE
Error during sending message from APRSDroid to telegram

### ISSUE THREAD

**Issue by abalashov78** [hemna/aprsd-telegram-plugin#5]
Hi all!

There is an error in version from 6yh August during sending a message from APRSDroid:

s.log:log:142
2024-08-12 16:19:40.464 | TXAck-R3TOC-1-26   | INFO     | TX -> AckPacket:26 (1 of 3) R3TOC -> R3TOC-1 | aprsd.packets.log:log:142
2024-08-12 16:19:40.469 | ProcessPKT         | INFO     | TelegramChatPlugin Plugin | aprsd_telegram_plugin.telegram:process:174
2024-08-12 16:19:40.473 | ProcessPKT         | INFO     | ['tg', 'abalashov78', 'test5'] | aprsd_telegram_plugin.telegram:process:191
2024-08-12 16:19:40.476 | ProcessPKT         | ERROR    | Plugin <class 'aprsd_telegram_plugin.telegram.TelegramChatPlugin'> failed to process packet argument of type 'NoneType' is not iterable | aprsd.plugin:filter:238
2024-08-12 16:19:40.479 | ProcessPKT         | ERROR    | argument of type 'NoneType' is not iterable | aprsd.plugin:filter:243
Traceback (most recent call last):

  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fc11919a3b0>
    └ <APRSDPluginProcessPacketThread(ProcessPKT, started 140467031238208)>
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function APRSDThread.run at 0x7fc117d67e20>
    └ <APRSDPluginProcessPacketThread(ProcessPKT, started 140467031238208)>
  File "/home/alex/.local/lib/python3.10/site-packages/aprsd/threads/aprsd.py", line 51, in run
    can_loop = self.loop()
               │    └ <function APRSDProcessPacketThread.loop at 0x7fc117bf1c60>
               └ <APRSDPluginProcessPacketThread(ProcessPKT, started 140467031238208)>
  File "/home/alex/.local/lib/python3.10/site-packages/aprsd/threads/rx.py", line 176, in loop
    self.process_packet(packet)
    │    │              └ MessagePacket(_type='MessagePacket', from_call='R3TOC-1', to_call='R3TOC', addresse='R3TOC', format='message', msgNo='26', ac...
    │    └ <function APRSDProcessPacketThread.process_packet at 0x7fc117bf1cf0>
    └ <APRSDPluginProcessPacketThread(ProcessPKT, started 140467031238208)>
  File "/home/alex/.local/lib/python3.10/site-packages/aprsd/threads/rx.py", line 224, in process_packet
    self.process_our_message_packet(packet)
    │    │                          └ MessagePacket(_type='MessagePacket', from_call='R3TOC-1', to_call='R3TOC', addresse='R3TOC', format='message', msgNo='26', ac...
    │    └ <function APRSDPluginProcessPacketThread.process_our_message_packet at 0x7fc117bf1f30>
    └ <APRSDPluginProcessPacketThread(ProcessPKT, started 140467031238208)>
  File "/home/alex/.local/lib/python3.10/site-packages/aprsd/threads/rx.py", line 289, in process_our_message_packet
    results = pm.run(packet)
              │  │   └ MessagePacket(_type='MessagePacket', from_call='R3TOC-1', to_call='R3TOC', addresse='R3TOC', format='message', msgNo='26', ac...
              │  └ <function PluginManager.run at 0x7fc117bc8160>
              └ <aprsd.plugin.PluginManager object at 0x7fc11767e830>
  File "/home/alex/.local/lib/python3.10/site-packages/aprsd/plugin.py", line 500, in run
    return self._pluggy_pm.hook.filter(packet=packet)
           │    │          │    │             └ MessagePacket(_type='MessagePacket', from_call='R3TOC-1', to_call='R3TOC', addresse='R3TOC', format='message', msgNo='26', ac...
           │    │          │    └ <HookCaller 'filter'>
           │    │          └ <pluggy._hooks.HookRelay object at 0x7fc116bd53c0>
           │    └ <pluggy._manager.PluginManager object at 0x7fc116bd5120>
           └ <aprsd.plugin.PluginManager object at 0x7fc11767e830>
  File "/home/alex/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           │    │         │    │     │    │                  │       └ False
           │    │         │    │     │    │                  └ {'packet': MessagePacket(_type='MessagePacket', from_call='R3TOC-1', to_call='R3TOC', addresse='R3TOC', format='message', msg...
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'filter'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'filter'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'filter'>
  File "/home/alex/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'packet': MessagePacket(_type='MessagePacket', from_call='R3TOC-1', to_call='R3TOC', addresse='R3TOC', format='message', msg...
           │    │               │          └ [<HookImpl plugin_name='140467286921552', plugin=<aprsd.plugin.HelpPlugin object at 0x7fc116bd5150>>, <HookImpl plugin_name='...
           │    │               └ 'filter'
           │    └ <function _multicall at 0x7fc117bb1ea0>
           └ <pluggy._manager.PluginManager object at 0x7fc116bd5120>
  File "/home/alex/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [MessagePacket(_type='MessagePacket', from_call='R3TOC-1', to_call='R3TOC', addresse='R3TOC', format='message', msgNo='26', a...
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='140467312099584', plugin=<aprsd_telegram_plugin.telegram.TelegramChatPlugin object at 0x7fc1183d8100>>
> File "/home/alex/.local/lib/python3.10/site-packages/aprsd/plugin.py", line 236, in filter
    result = self.process(packet)
             │    │       └ MessagePacket(_type='MessagePacket', from_call='R3TOC-1', to_call='R3TOC', addresse='R3TOC', format='message', msgNo='26', ac...
             │    └ <function TelegramChatPlugin.process at 0x7fc1163c9cf0>
             └ <aprsd_telegram_plugin.telegram.TelegramChatPlugin object at 0x7fc1183d8100>
  File "/home/alex/.local/lib/python3.10/site-packages/aprsd_telegram_plugin/telegram.py", line 198, in process
    if username not in self.users:
       │               │    └ <aprsd_telegram_plugin.telegram.TelegramUsers object at 0x7fc11820f730>
       │               └ <aprsd_telegram_plugin.telegram.TelegramChatPlugin object at 0x7fc1183d8100>
       └ 'abalashov78'
  File "/home/alex/.local/lib/python3.10/site-packages/aprsd_telegram_plugin/telegram.py", line 60, in __contains__
    if item in self._shortcuts:
       │       │    └ None
       │       └ <aprsd_telegram_plugin.telegram.TelegramUsers object at 0x7fc11820f730>
       └ 'abalashov78'

TypeError: argument of type 'NoneType' is not iterable
2024-08-12 16:19:40.605 | ProcessPKT         | WARNING  | Sending help! | aprsd.threads.rx:process_our_message_packet:330
2024-08-12 16:19:40.609 | TX-R3TOC-1-5165    | INFO     | TX -> MessagePacket:5165 (1 of 3) R3TOC -> R3TOC-1 : Unknown command! Send 'help' message for help | aprsd.packets.log:log:142

**Comment by abalashov78** [comment]
Installed versions:
aprsd                        3.4.0
aprsd-telegram-plugin        1.2.3
python-telegram-bot          13.15

**Comment by abalashov78** [comment]
Solution: use next format for shortcuts:
shortcuts = 'ab:abalashov78'
